[tool.black]
line-length = 100
exclude = '''
/(
  | migrations
  | \.git
  | \.github
  | node_modules
  | mypy_cache
)/

'''


[tool.isort]
profile = "black"
multi_line_output = 3
skip = [".gitignore", ".dockerignore"]
extend_skip = ["migrations"]